replicaCount: 3

image:
  repository: hyperion/rag-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

vectorStore:
  type: milvus
  replicas: 2
  resources:
    limits:
      memory: 4Gi

llmGateway:
  resources:
    requests:
      gpu: 1

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  PROMETHEUS_ENDPOINT: "http://prometheus:9090/api/v1/write"  # Docker service name
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"

env:
  PROMETHEUS_ENDPOINT: "http://prometheus:9090/api/v1/write"  # Docker service discovery
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  PROMETHEUS_TOKEN: ""  # Clear unused authentication

env:
  PROMETHEUS_ENDPOINT: "http://prometheus:9090/api/v1/write"  # Match Docker service name
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"

env:
  PROMETHEUS_ENDPOINT: "http://prometheus:9090/api/v1/write"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"

env:
  PROMETHEUS_ENDPOINT: "http://prometheus:9090/api/v1/write"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"