apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyperion.fullname" . }}
  labels:
    {{- include "hyperion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hyperion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hyperion.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VECTOR_STORE_ADDRESS
              value: {{ .Values.vectorStore.address }}